[functions]
  directory = "functions"                # folder where api.js lives
  external_node_modules = ["express","axios"]

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
  force  = true
