---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: http://localhost:3000/data
polling_headers: ''
id: 96340
name: MetroFresh ATL Soups
refresh_interval: 1440
